name: Trigger-me-by-curl

on: 
  repository_dispatch:
    types: do-something
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Hello"
